### ISSUE TITLE
New poetry-based virtual environment expecting specific versions of non-Python libraries to exist

### ISSUE THREAD

**Issue by chartjes** [mozilla/normandy#2167]
After creating a virtual environment using poetry (following the directions in the documentation) the API contract tests I wrote are generating an "image not found" error that I believe is related to psycopg2 expecting a specific version of libopenssl to be installed locally.

```
pytest -v --server=https://localhost:8000 contract-tests/v1_api/
Traceback (most recent call last):
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 20, in <module>
    import psycopg2 as Database
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: dlopen(/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/psycopg2/_psycopg.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/psycopg2/_psycopg.cpython-37m-darwin.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/bin/pytest", line 10, in <module>
    sys.exit(main())
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/_pytest/config/__init__.py", line 71, in main
    config = _prepareconfig(args, plugins)
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/_pytest/config/__init__.py", line 221, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/_pytest/helpconfig.py", line 89, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/_pytest/config/__init__.py", line 736, in pytest_cmdline_parse
    self.parse(args)
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/_pytest/config/__init__.py", line 943, in parse
    self._preparse(args, addopts=addopts)
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/_pytest/config/__init__.py", line 900, in _preparse
    early_config=self, args=args, parser=self._parser
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/pytest_django/plugin.py", line 335, in pytest_load_initial_conftests
    _setup_django()
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/pytest_django/plugin.py", line 223, in _setup_django
    django.setup()
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/chartjes/mozilla/normandy/normandy/recipes/models.py", line 6, in <module>
    from django.contrib.auth.models import User
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/django/db/models/base.py", line 117, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/django/db/models/base.py", line 321, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/django/db/models/options.py", line 204, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/django/db/utils.py", line 201, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/django/db/utils.py", line 110, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 24, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: dlopen(/Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/psycopg2/_psycopg.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Users/chartjes/Library/Caches/pypoetry/virtualenvs/normandy-Gr84UL80-py3.7/lib/python3.7/site-packages/psycopg2/_psycopg.cpython-37m-darwin.so
  Reason: image not found
```

I have /usr/local/opt/openssl/lib/libssl.1.1.dylib on my system, installed using Homebrew on macos

**Comment by mythmon** [comment]
@chartjes can you please use code blocks to format the errors in these issues? It makes them a lot more readable.

As to your issue, I'm not sure what's going on. This seems OSX specific, and I'm not sure what to do about it.
